services:
    userservice:
         # image: userservice:v1
          container_name: user-service
          restart: unless-stopped
          depends_on :
                 -  redisservice
          networks:
                 - proj-network
          build:
            context: .
            dockerfile: ./user_service/Dockerfile
            
          env_file:
                 - ./user_service/.env
    
    nginxservice:
          #image: openresty:v1
          container_name: nginx-service
          restart: unless-stopped
          depends_on: 
                - postservice
                - userservice
                - mediaservice
          build:
            context: .
            dockerfile: ./api_gateway/Nginx/Dockerfile
          networks:
                 - proj-network
       
          ports:
                 - "80:80"
          volumes :
                 - ./api_gateway/Nginx/new.nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf   #bind mounts chnage sare refleceted
    postservice:
          #image: temp:v1
          container_name: post-service
          restart: unless-stopped
          depends_on :
              - rabbitmqservice
              - redisservice       
          build:
            context: .
            dockerfile: ./post-service/Dockerfile
          env_file:
                 - ./post-service/.env
          networks:
                 - proj-network
    mediaservice:
          #image: temp:v2
          container_name: media-service
          restart: unless-stopped
          depends_on: 
                   - rabbitmqservice
          build:
            context: .
            dockerfile: ./media-service/Dockerfile
          env_file:
                 - ./media-service/.env
          networks:
                 - proj-network
 
    rabbitmqservice:
         container_name: rabbitmq-service
         restart: unless-stopped
         build:
             context: .
             dockerfile : ./Rabbitmq/Dockerfile
         volumes:
              - ./Rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
              - rabbitmq-data:/var/lib/rabbitmq
         networks:
              - proj-network
         ports:
              - "5000:15000"
   
    redisservice:
         container_name: redis-service
         restart: unless-stopped
         build:
             context: .
             dockerfile : ./Cachelayer/Redis/Dockerfile
         volumes:
              - ./Cachelayer/Redis/redis.conf:/usr/local/etc/redis/redis.conf
              - redis-data:/data
         networks:
              - proj-network
    mcpclientservice:
         container_name: mcp-client-service
         restart: unless-stopped
         build:
             context: .
             dockerfile : ./chat-agent/mcp-client/Dockerfile
         networks:
              - proj-network
         env_file:
                 - ./chat-agent/mcp-client/.env
    mcpserverservice:
         container_name: mcp-server-service
         restart: unless-stopped
         build:
             context: .
             dockerfile : ./chat-agent/mcp-server/Dockerfile
         networks:
              - proj-network
         env_file:
                 - ./chat-agent/mcp-server/.env
   
    prometheus:
          image: prom/prometheus
          volumes:
               - "./LocalMonitoring/prometheus.yml:/etc/prometheus/prometheus.yml"
               - "prometheus_data:/prometheus"
          ports:
               - "9090:9090"
          networks:
              - proj-network
    node-exporter:
          image: prom/node-exporter
          networks:
               - proj-network
          ports:
               - 9100:9100
    #alert-manager:
         # image: prom/alertmanager
         # volumes:
         #      - "./alertmanager.yml:/alertmanager/alertmanager.yml"
         # networks:
             #  - proj-network
         # ports:
               #- 9093:9093
    cadvisor:
          container_name: cadvisor
          image: gcr.io/cadvisor/cadvisor:latest
          #network_mode: "host"
          ports:
               - "8080:8080"
          volumes: 
               - "/:/rootfs"
               - "/var/run:/var/run"
               - "/sys:/sys"
               - "/var/lib/docker/:/var/lib/docker"
               - "/dev/disk/:/dev/disk"
          privileged: true
          devices: 
               - "/dev/kmsg"
          networks:   
               - proj-network
     
    grafana:
          container_name: grafana
          image: grafana/grafana:latest
          #network_mode: "host"
          ports:
               - "3000:3000"
          environment:
               - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
               - DS_PROMETHEUS=prometheus
          volumes: 
               - "grafana-data:/var/lib/grafana"
               - "./LocalMonitoring/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml"
               - "./LocalMonitoring/dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json"
               - "./LocalMonitoring/default.yaml:/etc/grafana/provisioning/dashboards/default.yaml"
          privileged: true
          depends_on:
               - prometheus
          networks :
               - proj-network
          
networks:

  proj-network:
          driver: bridge
volumes:
  redis-data:
  rabbitmq-data:
  prometheus_data:
  grafana-data: