events{}

http{
    server {
    listen portno ;
    #server_name api.example.com; host header
    client_max_body_size 50M;

    set $jwt_secret  "your value here" ;

    location /api/v1/auth/ {

        
        proxy_pass http://ip:port/auth/;         
       
        proxy_pass_request_headers on;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        
        proxy_set_header X-Forwarded-Proto $scheme;
        ;
       
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }  
     location /api/v1/post/ {

        
        
        access_by_lua_file /usr/local/openresty/lua/auth.lua
;

        proxy_set_header X-User-ID $http_x_user_id;
        proxy_pass http://ip:port/post/;
        
        

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
       
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;

        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    } 
    location /api/v1/upload/ {

        
        
        access_by_lua_file /usr/local/openresty/lua/auth.lua
;

        proxy_set_header X-User-ID $http_x_user_id;
        proxy_pass http://ip:port/upload/;
        
        

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
       
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;

        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    } 
          }
    } 