events{}
env JWT_SECRET;
http{
    server {
    listen 80 ;
    

    

    location /api/v1/auth/ {#literal preix match use trailing /

        
        
       #access_by_lua_block {
        #local cookie = ngx.var.http_cookie

        #ngx.log(ngx.ERR, "incoming cookie: ", cookie or "nil")

        #if cookie then
        #    ngx.req.set_header("Cookie", cookie)
        #end
        #  }

        
        proxy_pass http://ip:port/auth/;          #rewritepath
       # proxy_set_header X-User-ID $user_id;
        #proxy_set_header X-User-Role $token_type;
        #proxy_set_header Cookie $http_cookie;
        proxy_pass_request_headers on;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        
        proxy_set_header X-Forwarded-Proto $scheme;
        #proxy_set_header X-Forwarded-Host $host;
       
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }  
     location /api/v1/post/ {

        
        
        access_by_lua_file /usr/local/openresty/lua/auth.lua
;

        proxy_set_header X-User-ID $http_x_user_id;
        proxy_pass http://ip:port/post/;
        
        

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
       
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;

        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    } 
          }
    } 