apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: rabbitmq-external-secret
  namespace: backendmicro

spec:

  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore

  target:
    name: rabbitmq-secret
    creationPolicy: Owner

  data:        #ssm has stored them a s json

  - secretKey: RABBITMQ_PORT   #name in secret envfrom willmake ths same name as env varibale
    remoteRef:
      key: prod/backendmicro/rabbitmq-service/
      property: RABBITMQ_PORT  #propr anme cna eb diff from actual env value but do avoid confusion keep the same name

  - secretKey: RABBIRMQ_MANAGEMENT_PORT
    remoteRef:
      key: prod/backendmicro/rabbitmq-service/
      property: RABBIRMQ_MANAGEMENT_PORT

