apiVersion : apps/v1
kind : Deployment
metadata : 
       name : media-deployment
       namespace : backendmicro 
       labels: 
           app: media
spec:
   replicas : 3
   selector :
        app : media
   strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
   template : 
        metadata : 
              label :
                  app : media
                      
        spec :
           containers :
                    -  name : media-container
                       image: <accountid>.dkr.ecr.<ecr_region>.amazonaws.com/<reponame>/media-service:1.0.0
           envFrom:
                    - secretRef:
                               name: media-secret
                    - configMapRef:
                               name: media-config
           ports:
                  - name: http
                    containerPort: 3003

           readinessProbe:
                           httpGet:
                              path: /health
                              port: http
                              scheme: HTTP
                           initialDelaySeconds: 5
                           periodSeconds: 10
                           timeoutSeconds: 2
                           failureThreshold: 3
                           successThreshold: 1
