
bind 

port 

protected-mode 

tcp-backlog 

timeout 

tcp-keepalive 




#aclfile /usr/local/etc/redis/users.acl



maxmemory 

maxmemory-policy 



dir  




save 
save 
save 


dbfilename

rdbcompression 

rdbchecksum 




appendonly 

appendfilename 


appendfsync 



stop-writes-on-bgsave-error 




maxclients 





databases 


lazyfree-lazy-eviction 
lazyfree-lazy-expire 
lazyfree-lazy-server-del 




loglevel 

logfile 




slowlog-log-slower-than 

slowlog-max-len 




latency-monitor-threshold 




activedefrag 


stop-writes-on-bgsave-error 