apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  rabbitmq.template.conf: | # multi line strings in kub yml|
           listeners.tcp.default = ${RABBITMQ_PORT}
           management.tcp.port = ${RABBIRMQ_MANAGEMENT_PORT} 