apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  redis.template.conf: |                   
                bind 0.0.0.0
                port 3006
                protected-mode no
                tcp-backlog 511
                timeout 0
                tcp-keepalive 300
                maxmemory 100m
                maxmemory-policy allkeys-lru
                dir /data   
                save 900 1
                save 300 10
                save 60 10000
                dbfilename dump.rdb
                rdbcompression yes
                rdbchecksum yes
                appendonly yes
                appendfilename appendonly.aof
                appendfsync everysec
                stop-writes-on-bgsave-error yes
                maxclients 1000
                databases 2
                lazyfree-lazy-eviction yes
                lazyfree-lazy-expire yes
                lazyfree-lazy-server-del yes
                loglevel notice
                logfile /data/redis.log
                slowlog-log-slower-than 10000
                slowlog-max-len 256
                latency-monitor-threshold 100
                activedefrag yes




              