name: Infrastructure CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Target environment
        required: true
        type: environment

      action:
        description: Terraform action
        required: true
        type: choice
        options:
          - plan
          - apply
          - destroy
        default: plan

      terraform_version:
        description: Terraform version
        required: true
        type: string
        default: "1.9.8"

      confirm_destroy:
        description: Confirm infrastructure destruction
        required: false
        type: boolean
        default: false

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-${{ inputs.environment }}
  cancel-in-progress: false

env:
  
  TF_VERSION: ${{ inputs.terraform_version }}

jobs:

  plan:
    name: Terraform Plan
    if: (inputs.action == 'plan' || inputs.action == 'apply' )&& github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_tf_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
     #region for making region specific api calls with credentials of tah role successfull if permssion policy of that role allows note
     #already have credentials  of that role(github oidc has been configured before this cd)  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{env.TF_VERSION }}

      - name: Terraform Init
        working-directory: infra/terraform
        run: terraform init

      - name: Terraform Format Check
        working-directory: infra/terraform
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        working-directory: infra/terraform
        run: terraform validate

      - name: Terraform Plan
        id: plan
        working-directory: infra/terraform
        run: |
          terraform plan \
            -detailed-exitcode \
            -out=tfplan \
            -var="aws_eksvpcsglb_region=${{ secrets.AWS_REGION}}" \
            -var="aws_account_id=${{ secrets.AWS_accountid }}" \
            -var="aws_secret_region=${{ secrets.AWS_SECRET_REGION }}" \
            -var="aws_ecrimage_region=${{ secrets.AWS_ECR_REGION }}" \
            -var="ecrrepo_name=${{ secrets.AWS_ECR_REPONAME }}" \
            -var="github_token=${{ secrets.GITHUB_TOKEN }}" \
            -var="github_username=${{ secrets.GITHUB_USERNAME }}" 

        continue-on-error: true

      - name: Check Plan Result
        if: steps.plan.outcome == 'failure'
        run: |
          echo "Terraform plan failed."
          exit 1
 # here shell exit stops the whole flow if one step fails all do 
      - name: Upload Terraform Plan
        if: inputs.action == 'apply'
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: infra/terraform/tfplan     #tfplan is generated by plan as out=tfplan in work dir
          retention-days: 1
      #only upload the generated file if user selcetd apply

  apply:
    name: Terraform Apply
    if: inputs.action == 'apply' && github.ref == 'refs/heads/main'
    needs: plan
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
                role-to-assume: ${{ secrets.AWS_tf_ROLE_ARN }}
                aws-region: ${{ secrets.AWS_REGION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

    
      - name: Terraform Init
        working-directory: infra/terraform
        run: terraform init

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: infra/terraform/tfplan

      - name: Terraform Apply
        working-directory: infra/terraform
        run: terraform apply -auto-approve tfplan


  destroy:
    name: Terraform Destroy
    if: inputs.action == 'destroy' && inputs.confirm_destroy && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses :  aws-actions/configure-aws-credentials@v4
        with:
              role-to-assume: ${{ secrets.AWS_tf_ROLE_ARN }}
              aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

   
      - name: Terraform Init
        working-directory: infra/terraform
        run: terraform init

      - name: Terraform Destroy
        working-directory: infra/terraform
        run: |
          terraform destroy \
            -auto-approve \
            -var="aws_account_id=${{ inputs.AWS_accountid }}" \
            -var="aws_secret_region=${{ secrets.AWS_SECRET_REGION }}" \
            -var="aws_ecrimage_region=${{ secrets.AWS_ECR_REGION }}" \
            -var="ecrrepo_name=${{ secrets.AWS_ECR_REPONAME }}" 